### ISSUE TITLE
unexpected EOF while parsing upon input.

### ISSUE THREAD

**Issue by goleary** [guenter-r/calendar_file_splitter#1]
I exported an ICS using [this](https://chrome.google.com/webstore/detail/birthday-calendar-exporte/imielmggcccenhgncmpjlehemlinhjjo/related?hl=en).

When I try to run the script using:
`python select_contacts_from_ics.py birthday-calendar.ics`

I get prompted with this:
`relevant? y (YES) / (NO) any other key`

and no matter what input I provide (`y`, `n`, `Enter`) I end up seeing some sort of error:
```
Traceback (most recent call last):
  File "select_contacts_from_ics.py", line 36, in <module>
    user_input = input()
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing


### env
Macbook air M1 macOS v11.3
python 2.7.16
zsh

**Comment by guenter-r** [comment]
Good catch thanks! It seems the pattern has changed. The problem should be fixed (yesterday tested on Windows 10 and Ubuntu 21.04)
Please close the issue if the script is working fine now.

**Comment by guenter-r** [comment]
tested on macbook air m1 as well

**Comment by goleary** [comment]
Cool, thanks for fix it!
